### PR TITLE
Sean Cavanaugh Assignment 1 commit 1

### PR DESCRIPTION
**Pull request by seancava**
Please review my assignment

### CODE REVIEW

**Comment by jamdon** [comment]
Hi Sean. It looks like there are still some linting errors of various sorts remaining. Did you need more time to go through them or did you have any specific questions about how to address them? You can also view the recording in the recordings section of the class Github page Wiki to see more about addressing some of the linting issues you still have here. Let me know if you want it graded as-is or push an update if you want to correct the rest of the linting issues.

**Comment by seancava** [comment]
Hey James 
I’ve corrected the remaining errors except for 1. I couldn’t figure it out, any ideas? I’ve committed the updates, however I can’t seem to create a pull request at the moment. Please review my latest commit and let me know what you think.

Thanks,
Sean

**Comment by jamdon** [comment]
Your last linting error is happening because you removed the getRadiusLatLng method from the file. Refer to the original version of the file to see what I mean.

**Comment by jamdon** [comment]
Most of this looks good. The only problem was removing the getRadiusLatLng method, which resulted in an additional linting error. 👍

**Pull request closed without merging**
